### ISSUE TITLE
新增产品版本

### ISSUE THREAD

**Issue by cuisongliu** [sealyun-market/marketctl#1]
1. 新增产品版本

    > POST /openapi/v1/classes/{{product_class}}/products/{{product_name}}/versions
    >
    > Content-Type: application/json
    >
    >AccessToken: {{access_token}}
   

    ```
   {
     "name": "v1.19.1",
     "url": "http://baidu.co.",
     "price": 0.01,
     "sort": 11901
   }

    ```

**Comment by fanux** [comment]
markdown的说明 这些参数有不

**Comment by cuisongliu** [comment]
这个只是加版本的。Markdown的那个接口应该是加产品的那块去写，这块不用写markdown
